### ISSUE TITLE
Support Needed for Nonstandard Port in OwnCloud URL

### ISSUE THREAD

**Issue by mouser2017** [mvysny/photocloud-frame-slideshow#5] opened 2017-03-16 20:33 UTC
I've set up DDNS and port forwarding to successfully access my OwnCloud server remotely.  I'm using a different port to do so and that is working in web browsers.  However, when I try to set up this server in your application, it is giving an error:

Error
Failed to connect:
sk.baka.photoframe.util.IOExceptionWithCause: list / failed: -1
HOST_NOT_AVAILABLE

I've entered the URL as https://1.2.3.4:4444/ where 1.2.3.4 is the IP and 4444 is the nonstandard port.

This syntax with the port does not appear to work.

I tested with the internal IP, let's say 192.168.1.10 as an example and had the following occur:
https://192.168.1.10 - works
https://192.168.1.10:443 - does not work

I wanted to use a different port for my owncloud server remotely.  

Can this be supported?

Thanks,
mouser2017

**Comment by mvysny** [comment] 2017-03-17 05:10
Hi, thanks for letting me know and I apologise for the bug. I also tend to use dyndns and port forwarding to access my owncloud server and it works. Yet I must admit that I do not specify the port.

Let me test the test case with explicit port number, maybe there's some nasty bug in this regard...

**Comment by mvysny** [comment] 2017-03-20 18:54
Reproduced.

**Comment by mvysny** [comment] 2017-03-21 06:13
Huh, this is weird. On my older android 5.1 connecting to port 8899 works, while on my Android 7 it fails with the same exception as you described. Talk about Android compatibility :(
Going to investigate what's causing this.

**Comment by mouser2017** [comment] 2017-03-21 16:46
For completeness, the old devices I'm using are running Android 4.4.4. That's where I saw the issue.

**Comment by mvysny** [comment] 2017-03-21 18:32
OOookay, now it works for me on Android 7 as well, what the hell... maybe this is actually a configuration issue in the Owncloud? It is really important that the `config.php` file contains precisely the same host name and port which the PhotoCloud client will use, for example:

```
  array (
    0 => 'localhost:8899', 1 => '192.168.100.12:8899',
  ),
```
Note that you MUST include the port, otherwise this won't work. This may be the root of our issues.

I have performed a clean installation of Owncloud in a Docker. Just follow the following steps:

1. `docker run --rm -ti -p 8899:80 owncloud:latest /bin/bash`
2. In the Docker container, run `/entrypoint.sh apache2-foreground` - this will launch OwnCloud. In your browser, open http://localhost:8899 and select any username and password you like. This will create the `config.php` file.
3. In Docker, press `CTRL+C` to kill OwnCloud server. This will take some time.
4. I am doing this on my local Wifi+LAN. My computer running Docker has IP of 192.168.100.12, so I'll use that.
5. In Docker, we will edit the `config.php` to add the computer's IP. Otherwise OwnCloud will reject connections from PhotoCloud and will fail with 400.
6. In Docker, run `sed -i "s/'localhost:8899',/'localhost:8899', 1 => '192.168.100.12:8899',/g" config/config.php`, replacing your IP properly. Note that you must include the port.
7. Verify the new `config.php` by running `cat config/config.php` in Docker
8. In Docker, run again `/entrypoint.sh apache2-foreground`
9. In PhotoCloud, add OwnCloud server: type in http://192.168.100.12:8899 - note that you must use the IP:PORT exactly as stated in config.php. Also please make sure that the URL does not end with a slash.
10. Type in username/password you entered at step 2. The PhotoCloud should connect and should allow you to browse files in the demo account.

**Comment by mouser2017** [comment] 2017-03-22 04:32
I'm also translating the port right now.  So my public port is something like 4444 where the internal port is 443.  I don't think this is an OwnCloud issue though.  I did make a change in OwnCloud such that it is now configured with <ddns host name>:4444 for example.  I'm able to connect from external sources with a browser just fine.  However, the app is still not connecting properly.  I'm continuing to receive the same error as before: 
Failed to connect:
sk.baka.photoframe.util.IOExceptionWithCause: list / failed: -1
HOST_NOT_AVAILABLE

**Comment by mvysny** [comment] 2017-03-22 05:09
Ok, since I now cannot reproduce the issue, I need stack Trace of the exception from your phone logs. Also please check your owncloud log for any access violations.

**Comment by mvysny** [comment] 2017-03-22 08:23
I have just published an updated version of PhotoCloud (1.7.31) which should hopefully report more accurate error message on OwnCloud error.

**Comment by mouser2017** [comment] 2017-03-23 02:44
Well, guess what?  I updated to 1.7.31 and configured OwnCloud and it worked!  I'll do some more testing (hopefully tomorrow), but it appears to be working now. Awesome!  I'll try to test out the screen dimming option for night sometime soon as well. Thanks for all of your work.

**Comment by mvysny** [comment] 2017-03-23 04:30
Wow, that's unexpected, since I actually have fixed nothing related to this bug - I only have improved error reporting. Anyways, I'm happy that it works :) closing the bug, please reopen with more info (client stack Trace and server log) when the issue reappears.

**Closed by mvysny** 2017-03-23 04:30 UTC
Labels: bug, user feedback needed
