### ISSUE TITLE
Slideshow Stops and Quits randomly

### ISSUE THREAD

**Issue by ChezThomas** [mvysny/photocloud-frame-slideshow#82] opened 2018-03-08 06:27 UTC
I recently installed on 2 android tablet the paid version of the program.
On one of the tablet everything works as expected and smoothly with very rare crash (not more than any other app playing 24h/day)
But on the second one, somehow even I replicated exactly the same setup, We are experiencing repeated crash of the program when playing a slideshow usually after 15/20min (not always at the exact same time).
Would anyone have any idea on what could be done to fix that issue ? Or what could I share to you (debug?) to further explores the source of the problem.
Thanks a bunch in advance.
T.

**Comment by mvysny** [comment] 2018-03-08 06:38
Hi, sorry for the crash. Does the app crash in a sense that it disappears from the screen without any information whatsoever, or is there some kind of an error message? If there is an error message, can you please paste it here?

**Comment by ChezThomas** [comment] 2018-03-08 08:36
Thanks a lot for your prompt reply :-)
So basically from my understanding it crashes without any information and goes back on the springboard. 
Any way to check and upload to you the log files?

**Comment by mvysny** [comment] 2018-03-08 09:18
Wow that's new. It actually should upload the error log automatically, but this looks like a hard crash - it looks like Android just re-launches the app after such a crash.

You can obtain the log by enabling the developer options on your phone, enabling USB debugging, downloading the Android SDK and running `adb logcat`. This tutorial looks nice: https://logmatic.io/blog/a-how-to-guide-to-debugging-with-android-logcat/

**Comment by mvysny** [comment] 2018-04-14 04:24
I've created a FAQ on how to obtain the stacktrace of the crash: http://www.android-photo-frame.eu/faq.html section "Reporting crashes". Please follow the steps and paste the stacktrace here.

**Comment by mvysny** [comment] 2018-04-14 04:25
This could be a duplicate of #88 - what phone/Android version do you have please?

**Comment by mvysny** [comment] 2018-04-14 04:27
Closing as inactive, please reopen when you can provide the stacktrace.

**Closed by mvysny** 2018-04-14 04:27 UTC
Labels: bug, user feedback needed

**Comment by ChezThomas** [comment] 2018-07-16 03:40
Hi,
We finally figured out a way for the previous error.
But now the client is getting a new one.
Not sure if you can help us to solve it :-)
You can see the error message at the bottom of the photo of the screen.

Again, thanks for your help!


T.
