### ISSUE TITLE
Screen freezes for some time when ending slideshow

### ISSUE THREAD

**Issue by JesperJanssen** [mvysny/photocloud-frame-slideshow#58] opened 2017-12-24 10:27 UTC
After the latest update the slideshow freezes for about 10-30 seconds when touching the screen in daydream mode. This means you have to wait some time before you can use the tablet for other stuff.

The same thing happens when you touch the screen followed by pressing the "back" button on the tablet when playing a slideshow within the app. The screen freezes for +/- 30 seconds before you return to the menu or the app crashes.

I also send a crash report about this with the app.

**Comment by mvysny** [comment] 2017-12-24 10:51
Hi, thanks for letting me know, sorry about that. Which stream type are you using?

**Comment by mvysny** [comment] 2017-12-24 14:42
I have a hunch what may be the cause. Yet Christmas is an incredibly busy season so I'll need more time for this. Meanwhile have a Merry Christmas :)

**Comment by mvysny** [comment] 2017-12-25 10:50
Thank you, found the ANR report at Google Play. The problem is that sometimes the internal database IO can stall for a long time:
```
  at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow (Native method)
  at android.database.sqlite.SQLiteConnection.executeForCursorWindow (SQLiteConnection.java:930)
  at android.database.sqlite.SQLiteSession.executeForCursorWindow (SQLiteSession.java:836)
  at android.database.sqlite.SQLiteQuery.fillWindow (SQLiteQuery.java:62)
  at android.database.sqlite.SQLiteCursor.fillWindow (SQLiteCursor.java:143)
  at android.database.sqlite.SQLiteCursor.getCount (SQLiteCursor.java:132)
  at android.database.AbstractCursor.moveToPosition (AbstractCursor.java:219)
  at android.database.AbstractCursor.moveToFirst (AbstractCursor.java:258)
  at sk.baka.photoframe.fsimpl.DatabaseBackedBag.poll (DatabaseBackedBag.kt:53)
  at sk.baka.photoframe.fsimpl.DatabaseBackedBag.poll (DatabaseBackedBag.kt:29)
  at sk.baka.photoframe.stream.BagWrapper.take (BlockingBag.kt:107)
  at sk.baka.photoframe.blockingchannel.BufferedChannel$Companion$drainIgnoringExceptions$1.invoke (BufferedChannel.kt:80)
  at kotlin.sequences.SequencesKt__SequencesKt$generateSequence$1.invoke (Sequences.kt:578)
  at kotlin.sequences.GeneratorSequence$iterator$1.calcNext (Sequences.kt:517)
  at kotlin.sequences.GeneratorSequence$iterator$1.hasNext (Sequences.kt:535)
  at sk.baka.photoframe.blockingchannel.BufferedChannel.close (BufferedChannel.kt:100)
  at sk.baka.photoframe.util.UtilsKt.closeQuietly (Utils.kt:34)
  at sk.baka.photoframe.stream.FileDownloadingIterator.close (FileSystemCrawler.kt:191)
```

**Comment by mvysny** [comment] 2017-12-25 10:53
Fixed in 1.10.6

**Closed by mvysny** 2017-12-25 10:53 UTC
Labels: bug

**Comment by JesperJanssen** [comment] 2017-12-25 19:21
Wow you fixed this issue quickly. And that during the Christmas period. Thanks a lot. I think you are one of the app developers who are the fastest when it comes to responding to customers (or bug reports). This app should only receive 4 or 5 star ratings from everbody (5 stars in my opinion).

I will try it out as soon as the app is updated and let you know if it is fixed. Btw; I'm using OneDrive for storing my photos.

**Comment by mvysny** [comment] 2017-12-27 07:37
Thanks :) yeah I'm quite fond of this project even though it doesn't earn much. Anyway, merry Christmas and happy New year!
