### ISSUE TITLE
Multiple Devices

### ISSUE THREAD

**Issue by simonchunk** [mvysny/photocloud-frame-slideshow#86] opened 2018-03-29 04:00 UTC
Love this app. I have purchased on my phone, but the main reason was to use it on my Android boxes. They all run the same google account, but the nag screen appears on those like I haven't paid. 

Do I need to pay for each device? If that's the case, how do I change the device as they get old or fail?

**Comment by mvysny** [comment] 2018-03-29 04:41
That's certainly very unusual. The app should be automatically activated on all of your devices connected to the same Google account. You definitely do not need to purchase the app separately per device; a single purchase should unlock the app on all devices connected to that Google account.

The Google play app is responsible for communicating to the app whether it is unlocked or not. Do you have Google play installed on all of your devices? Can it connect to the internet to sync the purchases?

**Comment by simonchunk** [comment] 2018-03-29 04:43
Yes, they have Google and it can see that it is a purchase in my library.
Just doesn't unlock it... 🤔

**Comment by mvysny** [comment] 2018-03-29 04:46
Could it be that the phone has in fact multiple Google accounts? You may
need to run the app under the account under which it was purchased.

**Comment by mvysny** [comment] 2018-07-08 10:41
No feedback provided for more than 1 month, closing

**Closed by mvysny** 2018-07-08 10:41 UTC
Labels: question, user feedback needed

**Comment by droberg** [comment] 2018-08-10 17:02
I would like to reopen!

I have three units and at least two out of three is still nagging me to buy. I cannot buy it again (it reports an error).

Please advice

**Comment by mvysny** [comment] 2018-08-12 08:27
What kind of error? Please paste the error text message here

**Comment by droberg** [comment] 2018-08-14 12:29
Hi

The error stated that I had already bought and couldn't buy again. However, after a few reboots the error disappeared and I cannot reproduce it so I cannot say for sure. 

I tried a fresh install on a forth device and it went flawlessly.

**Comment by mvysny** [comment] 2018-08-14 12:51
Hi ;)

PhotoCloud polls the purchase information from the Google Play application on your phone every time PhotoCloud is started. So after a reboot it should have figured out that it's already purchased, unless Google Play itself was feeding PhotoCloud fake data. I'd say that it was a glitch of Google Play. To confirm, please capture the log of your phone; there should be something like `unlock.remote_streams are now purchased` or `unlock.remote_streams are now NOT PURCHASED`. That's coming directly from Google Play and if this is incorrect, then Google Play is lying.

**Comment by droberg** [comment] 2018-08-19 15:08
Hmm.. Tried using catlog but it claims it needs root, which I don't have and probably wont mess with for this particular hardware.  

Now that it works it does not really matter, but it would have been nice to help out in case it shows out to be a general problem.

Over and out.
Per

**Comment by mvysny** [comment] 2018-08-20 05:56
> Hmm.. Tried using catlog but it claims it needs root, which I don't have and probably wont mess with for this particular hardware.

True, the Android app `catlog` requires root. Don't use any Android app and don't root your phone - instead, just connect your phone via USB cable to your PC, enable debugging mode and install `adb`: https://logmatic.io/blog/a-how-to-guide-to-debugging-with-android-logcat/
