### ISSUE TITLE
Change way EXIF info is displayed on screensaver/daydream 

### ISSUE THREAD

**Issue by JesperJanssen** [mvysny/photocloud-frame-slideshow#28] opened 2017-07-13 17:10 UTC
V.1.9.3

Is it possible to make a small menu for the different exif options so that everybody can choose what they want to display. For example for me displaying the file name is not necessary since it just a bunch of numbers.

Furthermore, I noticed that my folder names do not fit in the box you made for it. Could you increase the display box or even better just remove the box and let it just display the folder name and time it was taken. And I don't think it is necessary to display the tag names "file name" "folder name" "picture date" just only display the names or dates to make it look better. Something more like google chromecast backdrop: https://www.technobuffalo.com/wp-content/uploads/2014/10/chromecast-custom-backdrop-3.jpeg

And I agree that just displaying the gps coordinates does not make any sense unless you are able to translate them to country or places.

**Comment by mvysny** [comment] 2017-07-14 09:59
Hmm, interesting. It seems that there actually is a possibility to do reverse geocoding (obtaining street name from GPS coordinates) in Android for free: https://stackoverflow.com/questions/36302414/google-maps-geocoding-api-usage-limits-in-android-device
So perhaps I will be able to translate those into street name. Let me play with it.

**Comment by mvysny** [comment] 2017-07-14 10:01
Well, if I remove the box, then I believe the text will be unreadable on some images. However let me learn how ChromeCast copes with that.
I could enlarge the box, but that would interfere with the weather forecast box. But if I move the EXIF box to the upper-right corner, that would give us quite a lot of space. Let me play with this.

**Comment by mvysny** [comment] 2017-07-15 06:44
Reverse-geocoding (resolving latlon to street address) works really nicely in Android, implemented.

**Comment by JesperJanssen** [comment] 2017-07-15 06:50
True, removing the box makes the text for some images unreadable. However, this prevents screen burn in since the box is always at the same place in the picture. Or does the box also dissapears for a short period of time when a new photo is shown.

Since there is a lot of EXIF data for each picture would it be possible to let the users just select which EXIF data they would like to show. Otherwise the box will be very long/big.

I think it will look the best if you can chose from the following options:
- Folder name, which is essentially the album name
- Day and time photo was taken (and then displaying the months in text instead of numbers)
- Location photo was taken if you are able to reverse geocoding to an adres. I personally think the location should contain Country and City. For example, United States, New York. Adding an street adres will make it very long and possibly not correct (since gps coordinates could be off a little bit)

When displaying this info I would not display the tag with it since that would just use up more space. And I like the way Google does it with displaying the Folder name (=album name) a little bit bigger than the rest.

For example:
## Iceland 2015
6-July-2015

**Comment by mvysny** [comment] 2017-07-15 06:58
> True, removing the box makes the text for some images unreadable. 

Exactly. ChromeCast copes with this by artificially dimming the image and making the dim more powerful towards the bottom. You can see this effect in action on the screenshot you've provided. I don't think this is what we want ;)

> However, this prevents screen burn in since the box is always at the same place in the picture. Or does the box also dissapears for a short period of time when a new photo is shown.

I believe that screen burn is caused by white (or glaring) pixels. If this is true, then I believe that the box cannot cause screen burn since it dims underlying pixels towards pure black.

> Since there is a lot of EXIF data for each picture would it be possible to let the users just select which EXIF data they would like to show. Otherwise the box will be very long/big.

Actually you're right - the photo name will usually be some number randomly generated by the phone or camera. It thus probably makes no sense to show the file name. I'll thus show the parent folder name instead; I'll show the photo name only when the parent folder is empty (which is the case of Px500 pictures which actually are named properly but have blank parent folder).

Let me play with this a bit, I'll attach a screenshot soon.

**Comment by JesperJanssen** [comment] 2017-07-15 07:05
Great work Martin!

Sounds like an good idea to use the photo name only when no parent folder name is available.

I did not know Google was dimming the pictures in the bottom. But then again I do not use that function a lot I only see it when I stop using something on my Chromecast and my tv is still on.

Curious how the screenshot will look like

**Comment by mvysny** [comment] 2017-07-15 08:06
![device-2017-07-15-110354](https://user-images.githubusercontent.com/254091/28237666-97c5f008-694d-11e7-8e5d-b39698c906e7.png)

**Comment by JesperJanssen** [comment] 2017-07-15 08:33
Looks good!

Few questions:
- Will you make three options (boxes with checkmarks) for three different values (Folder name, date and geo info)?
- What happens when there is no Geo info available?
- How many characters fit into the box because I think some folder names and location information will not fit into this box)?
- Will there be an option to chose where in the screen you want to show this information (which corner)?

**Comment by mvysny** [comment] 2017-07-15 08:49
> Will you make three options (boxes with checkmarks) for three different values (Folder name, date and geo info)?

Probably not. It is easy to go overboard and make everything configurable, but that would make the app hellishly hard to test, and also hard to configure for the users. That's why I like to keep the configuration as simple as possible. Also if folder name was not shown, should I show date as bold/larger? Or make this configurable as well? Not so easy ;) I'd rather prefer to tune this functionality to some reasonable defaults which work for you.

> What happens when there is no Geo info available?

The box will shrink to only show the file name and the date. There will not be a blank row. This also will happen when the reverse geocoding fails (the device is offline or the connection timed out; I need to go to Google's server to convert GPS latlon to address).

> How many characters fit into the box because I think some folder names and location information will not fit into this box)?

Hard to say since the font is variable-width. I'd estimate around 30. If it won't fit, it will ellipsize

> Will there be an option to chose where in the screen you want to show this information (which corner)?

Currently nope. If you wish this info to be permanently moved to the upper-right corner, let me know. This would allow me to make the box larger a bit.

**Comment by JesperJanssen** [comment] 2017-07-15 18:49
When will I be able to test these improvements and new function (location using geo info)?

**Comment by mvysny** [comment] 2017-07-16 10:24
@JesperJanssen do you thus agree with the size and the location of the quick EXIF box?

**Comment by JesperJanssen** [comment] 2017-07-16 10:57
I think 30 characters will be enough for almost all folder names. 

And the left bottom corner is also the most suitable place since the right bottom corner is already taken by the date, time and weather.

**Comment by mvysny** [comment] 2017-07-16 11:11
Awesome. Implemented in 1.9.4, closing.

**Closed by mvysny** 2017-07-16 11:11 UTC
Labels: enhancement, user feedback needed
