### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by nascentt** [mvysny/photocloud-frame-slideshow#53] opened 2017-12-17 19:52 UTC
fatal error: java.util.concurrent.executionexception: java.lang.OutOfMemoryError: Failed to allocate

not sure if this is because of a memory leak or something, it seems to only be a 12mb file it tried to load.  I have seen this happen before also.

![screenshot_2017-12-17-19-44-38-362_sk baka photoframe](https://user-images.githubusercontent.com/1145722/34083171-d2a870de-e363-11e7-9752-ff4073814336.png)

**Comment by nascentt** [comment] 2017-12-17 20:42
This particular device is a 4gb RAM dedicated purpose tablet.

**Comment by mvysny** [comment] 2017-12-17 21:21
The problem with Android is that regardless the OS memory, it only provides 16mb of memory to an app, or 24mb if the app says it needs more. I have configured PhotoCloud to use the `android:largeHeap` but that's all I can do unfortunately - Android decides how much memory the app receives. I thought it is 24mb on all devices, but apparently this value differs per-device.

It would be interesting to see what value the `getLargeMemoryClass()` function returns on your device.

I am trying hard to load just the necessary images, but at any point I have to hold at least two-three images in memory (when you fling to history). I also downscale the images so that they fit on your screen. However that's not possible with RAWs. It would be interesting to see where exactly the OOM occurred. I'll try to check the current error reportings.

**Comment by mvysny** [comment] 2017-12-17 21:25
Unfortunately Crashlytics is really horrible and hides old reports, so I can't access the OOM reports. It would be great if you could obtain the stacktrace crash from your device and paste it here.

**Comment by nascentt** [comment] 2017-12-18 10:15
Tell me what to do and I'll do my best to help diagnose. Crazy you only get
16mb - the device has 4gb ram. The images are huge (dslr) so it sort of
makes sense.

The bigger problem is the app doesn't continue after the error. Would be
nice if you discarded the images in memory then start again rather than
just stay at the error screen.

I plan  on giving tablets to family as photoframes for Christmas but the
errors that halt images showing will confuse them as they're elderly. I
plan on it being non-interactive.

**Comment by mvysny** [comment] 2017-12-18 10:28
> Tell me what to do and I'll do my best to help diagnose. Crazy you only get
16mb - the device has 4gb ram. The images are huge (dslr) so it sort of
makes sense.

Yup I agree it's crazy :( 

Are those DSLR images RAWs by any chance? If yes, you can definitely convert them to jpegs - Android can then load jpegs and downscale them at the same time - that's very memory efficient.

> The bigger problem is the app doesn't continue after the error. Would be
nice if you discarded the images in memory then start again rather than
just stay at the error screen.

The problem with OutOfMemory is that not only the loader fails, the other concurrently running parts of the app typically fail as well (since there's no memory), so the app may be in some half-crashed unpredictable state. Therefore it's generally very dangerous to auto-repeat the OutOfMemory in particular. Of course PhotoCloud repeats less serious I/O errors, but it's really not recommend to repeat OutOfMemory.

> I plan  on giving tablets to family as photoframes for Christmas but the
errors that halt images showing will confuse them as they're elderly. I
plan on it being non-interactive.

I understand and I agree - the app should just run without any issues since it will probably run on a tablet hanged on a wall which nobody touches anymore. And it should exactly do that, with the exception of OutOfMemory errors...

**Comment by mvysny** [comment] 2017-12-22 20:08
Fixing #56 should help a bit with the memory usage.

**Comment by mvysny** [comment] 2017-12-23 16:04
With PhotoCloud 1.10.5 you can check how much memory Android gives to PhotoCloud (it's in the About dialog). I've found out that on my phone with 2gb of memory PhotoCloud receives a generous 256 MB; on my other phone with 3gb of memory PhotoCloud receives 512 MB. I have never experienced out of memory on my phones.

Can you check how much memory PhotoCloud receives on your device please?

**Comment by nascentt** [comment] 2017-12-23 16:32
384mb

**Comment by mvysny** [comment] 2017-12-23 17:12
That should be more than enough memory to run Photocloud...

**Comment by mvysny** [comment] 2017-12-26 05:12
This bug report illustrates the problem with handling out of memory errors quite well:
```
Fatal Exception: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
```
:)

**Comment by nascentt** [comment] 2017-12-28 23:34
the issues been happening more and more frequently in recent days, really bizarre.  2GB free currently

**Comment by nascentt** [comment] 2018-01-06 22:09
Something interesting I noted today regarding this.
For the last 24 hours my server was offline, so the photoframe couldnt
access the photo share.  This obviously meant that it cycled through the
cached images.
After 24 hours I got the server back up.  The tablet took a minute or so to
recognise the server and started streaming new pictures again.  Within
minutes  BAM "OutOfMemory". So I close all apps, free memory.  Restart the
slideshow and a few minutes passes BAM.

24 hours no issues... no access to photo share.  A few minutes of access to
photoshare and errors reoccur.

Surely that's not a coincidence right?  Whether it means that the cached
photos are small enough to fit in the memory whereas the photos it tries to
load from the server to big....or it's an issue with using too much ram
traversing the server heirachy...or something else.

That seems to give some sort of clue.  Also I use non default cache
settings, no idea if that might alter anything, such as thumbnail cache or
photo cache?  Maybe I should set those as default again?

**Comment by mvysny** [comment] 2018-01-07 08:29
> Surely that's not a coincidence right?  

Most probably it's not a coincidence. The photos are always cached downscaled to the resolution of the device screen. That makes sense since typically your device just hangs on a wall showing pictures; you typically do not zoom those pictures in. Downscaled versions also take up significantly less space in the cache.

As you say, apparently showing cached (downscaled) versions of images works rock solid for 24 hours straight; showing full-sized images from your storage fails with OOM. Apparently there is something wrong with the image decoder (since the decoder should downscale loaded images to the device resolution on-the-fly and should thus not take up lots of memory).

I have optimized the server hierarchy traversal and it should now use rather small amount of RAM; I'm guessing the largeness of those photos is the culprit here.

1. Are you sure that those large images aren't RAWs? RAW decoding does not support on-the-fly downscale and takes up enormous amount of memory. Please try to not to slideshow RAWs and let's see if it helps.
2. What kind of images are you showing? Number of pixels, pixel resolution, format (is it JPEG only?)

I'd propose the following:
1. Try to only show a folder with JPEGs with original size in the slideshow, no RAWs, and see if it helps.
2. If it doesn't, try imagemagick or other mass downscaler software to downscale a couple of images to, say, 1080p, and only show that folder, to see if it helps.

**Comment by nascentt** [comment] 2018-01-07 16:32
hmm I do have the "Include RAWs in slideshow unticked.  SO it should avoid
any RAW files right?

I can try step 2, but I guess due to having thousands of images I need to
test with individual folders first to confirm a confirm that is actually
affected.

**Comment by nascentt** [comment] 2018-01-07 16:33
images are from various devices, but mostly smartphone, and dslr

**Comment by mvysny** [comment] 2018-01-07 16:37
> hmm I do have the "Include RAWs in slideshow unticked.  SO it should avoid
any RAW files right?

True; PhotoCloud should ignore raw images.

> I can try step 2, but I guess due to having thousands of images I need to
test with individual folders first to confirm a confirm that is actually
affected.

I'd suggest to find a folder with biggest image, root the stream there and try the Slideshow whether it will crash or not.

A different question just came to my mind: are you perhaps using symlinks? Could it be that symlinks to parents are used, which creates an infinitely deep tree?

**Comment by nascentt** [comment] 2018-01-07 16:48
Interesting.   I do have a symlink - although it shouldn't cause an
infinite loop, as it points to another location...  Let me remove it for
now.
I'll search for the largest files and put thme in a folder and test.  I do
have some stray mp4 and raw in some of thee folders, does the app ignore
any movies be default?

**Comment by mvysny** [comment] 2018-01-07 16:53
Yes, the app should ignore all files except "png", "gif", "bmp", "jpg", "jpeg"

**Comment by nascentt** [comment] 2018-01-07 17:00
I just checked, the symlink was already gone, it was probably the first
thing I tried myself.

I guess I'll try random subfolders/large files until I find a folder that
causes the crash.

**Comment by mvysny** [comment] 2018-01-07 17:43
Thank you very much for your patience. At this point I have no idea what may be the cause of the OOM. Perhaps it is an image that is somehow corrupted; maybe a set of images. Unfortunately I can't reproduce the OOM and hence I can't hunt for such image myself, otherwise I would have done so. Meanwhile I will revisit the image loading code, perhaps there is something I have missed?

**Comment by mvysny** [comment] 2018-01-19 18:44
Added the setting in PhotoCloud 1.10.10; it's in Settings / Slideshow / Advanced. Closing; please feel free to reopen if you succeed in finding that pesky photo which causes this memory-related crash to occur.

**Closed by mvysny** 2018-01-19 18:44 UTC
Labels: bug, user feedback needed

**Comment by nascentt** [comment] 2018-01-23 19:44
Just to update.  I haven't had a single OutOfMemory error since enabling
this.  It might be a coincidence as it might not have hit whichever folder
that was causing it, but when I'd get it I'd then get it 30 times that day
and that hasn't happened yet.

**Comment by nascentt** [comment] 2018-03-03 11:13
One more update.  Not a single OutOfMemory error in the past 1-2 months.
Despite getting them on an hourly basis around christmas.
I also don't have the half resolution option enabled. Nor did I ignore any
directories.
