### ISSUE TITLE
get purchase picture - yet no purchase option

### ISSUE THREAD

**Issue by Brun059** [mvysny/photocloud-frame-slideshow#188] opened 2023-09-11 12:05 UTC
I thought I purchased photocloud - yet I get the purchase pop-up image (enthusiasm can only go so far...) 
and I cannot find the purchase option in setup. 
The about photocloud informs me that i have purchased, yet.. see above
![Screenshot_20230910_130632_PhotoCloud Slideshow](https://github.com/mvysny/photocloud-frame-slideshow/assets/29820365/9e54b1c8-f8d0-439c-be90-dc11b55b212a)

but anyway, still the best picture frame around...

**Comment by mvysny** [comment] 2023-09-11 15:42
Ooops, I'm really sorry about that.  Thank you for the screenshot, it shows that the subscriptions are registered properly by PhotoCloud. However, I have realised just today that there could be a brief window right after PhotoCloud is started, when the purchases may not be registered yet. If you start a slideshow during that brief window, the “Please Purchase” photo will be shown erroneously.

Could you please confirm this? You can do this by starting PhotoCloud but not running the slideshow just yet: first check the About screen to see that the subscriptions are fully registered, and only afterwards launching the slideshow. If I’m correct, the “Please Purchase” photo should no longer be shown.

**Comment by Brun059** [comment] 2023-09-11 17:48
I did a restart of the tablet - and got the same screen 
if it helps : I got the impression that the tablet did not change pictures (emphasis on impression ;-))  so I touched the screen (sometimes that helps) and then got the "please purchase" image
, 
![Screenshot_20230911_194018_PhotoCloud Slideshow](https://github.com/mvysny/photocloud-frame-slideshow/assets/29820365/3751083d-ee87-4df1-b0f8-6aa0f0788952)

**Comment by mvysny** [comment] 2023-09-12 04:14
I've pushed out PhotoCloud 1.15.2 which should hopefully fix this issue. Please update and let me know whether the issue is fixed. If the issue is not fixed right after update, please try to reboot your device once.

Closing as fixed, please reopen if the issue persists with PhotoCloud 1.15.2

**Closed by mvysny** 2023-09-12 04:14 UTC
Labels: bug

**Comment by Brun059** [comment] 2023-09-18 05:18
Sorry for answering only now, I was away. Thanks for the new version. I have not seen the message again, I guess you fixed is successfully. (and very quickly)
