### ISSUE TITLE
Android TV - Fail to discover samba server

### ISSUE THREAD

**Issue by nascentt** [mvysny/photocloud-frame-slideshow#69] opened 2018-01-22 20:18 UTC
Thank you so much for the Android TV version.  The ui is great, no issues with the remote at all.
However I am struggling to add a samba share to the gallery.  Whether I try a hostname or a direct ip, I get "unable to find samba servers: failed to connect: 0.0.0.0<00>/192.168.10.20 jcifs.util.transport.TransportException: Connection Timeout"

note 192.168.10.20 is nothing, it's not the samba server I've entered manually, nor the ip of the android tv client.

The samba server works fine with other photocloud client devices and the android tv can navigate to the samba server share with another app without issue.

App has both permissions enabled.  App works perfectly for a test from another source (500px)/

**Comment by mvysny** [comment] 2018-01-23 08:27
That looks weird. Let me try to reproduce it on my environment.

**Comment by mvysny** [comment] 2018-01-23 19:30
I have found out what the problem is. There are the following problems:

1. To list Samba servers, the device needs to connect to a computer hostnamed `..__MSBROWSE__.<01>` which manages the list of servers. Typically one PC assumes such role in a LAN network, by acquiring that hostname. However, this require a Microsoft-specific hostname resolution to be present in the device, which is apparently missing for Android TVs (even my TV can't resolve that computer and thus can't list all the samba servers). Remember that Microsoft create their own standard for everything.

2. To remedy that, you can enter the samba server IP manually into the field and then press the " --> " button. The problem is that the " --> " button was not focusable on the TV (my bad :-) ), thus you could not enter a custom IP and press the " --> " button to connect to the manually-entered server IP address such as `192.168.100.15` . This is now fixed.

3. PhotoCloud would then attempt to list a content of the first share, and this is bug number three - if the user had no access to read first share on your samba server, PhotoCloud would reject that user even though the user is valid and would be able to read some other share just fine. I have fixed this, simply by only trying to connect to the samba server itself, and not to a particular share.

Everything should be fixed in PhotoCloud 1.11 which should hopefully be released this week.

**Closed by mvysny** 2018-01-23 19:30 UTC
Labels: bug

**Comment by nascentt** [comment] 2018-01-23 19:39
You're awesome!

I'll look forward to the release.  Once I get it up and running on my
Shield I'll test it out on my other Android TV box.
