### ISSUE TITLE
Filter On Date

### ISSUE THREAD

**Issue by ScherlOMatic** [mvysny/photocloud-frame-slideshow#165] opened 2021-10-06 06:37 UTC
Hello,

I'm using the Nextcloud integration of your app, and I'm having an issue with the filtering of my pictures. I've tried various settings but somehow they are always getting ignored.

On my nextcloud drive the structure looks something like this Root-> Sub Folder-> Sub^2 Folder-> Sub^3 Folder -> Actual Pics
In the end I'd like the filtering also to work with the root folder but for testing I us Sub^3 Folder.
Nextcloud tells me that the last change here was made 3 days ago, and I also uploaded those files a few days ago. When I turn on "Filter on Date" and set "Show Not older Than" to let's say 7, I should still be able to see those files. And when I set this value to 1 those files should be gone, correct? But nope, no matter what the value is, I only see the purchase screen from your app.

Am I missing here something or do you have any idea what the problem might be? I also checked the timestamp on the filesystem and they are correct. Clearing the app cache doesn't change anything.

THX for your help and BR
Stefan

**Comment by mvysny** [comment] 2021-10-12 12:06
Hello,

  I'm sorry to hear that. The problem is that when PhotoCloud performs the photo filtering based on a date, the file system date of the photo file is taken into account, as opposed to the EXIF metadata date. On top of that PhotoCloud will only show the EXIF date and not the file-system date-of-creation date, so there's no way of telling why PhotoCloud filters out all of the photos (that's what's happening - if all photos are filtered out, PhotoCloud will only show the 'please purchase' image).

Another problem is that while the date-of-creation might be correct locally on your NextCloud, it could have been transferred incorrectly to PhotoCloud. However, there's no way of knowing that until PhotoCloud start showing the filesystem date of creation.

Could you please open another bug report in this respect (so that PhotoCloud starts showing the file-system date-of-creation date)?

**Comment by mvysny** [comment] 2022-11-17 10:25
Closing as stale.

**Closed by mvysny** 2022-11-17 10:25 UTC
Labels: bug, user feedback needed
