### ISSUE TITLE
SMB error, screendump attached

### ISSUE THREAD

**Issue by Brun059** [mvysny/photocloud-frame-slideshow#19] opened 2017-07-02 15:51 UTC
![screenshot_2017-07-02-17-40-27](https://user-images.githubusercontent.com/29820365/27771459-fd1a8a1c-5f4e-11e7-935b-dd55cfd3e5d6.png)

it cured itself after a reboot

**Comment by mvysny** [comment] 2017-07-02 15:59
Connection Timeout. This is most probably a networking error, or your server was down, or your device's wifi is acting up. Either way, there is little I can do in this situation, this is not caused by an error in my code. Closing as won't fix.

**Closed by mvysny** 2017-07-02 15:59 UTC

**Comment by Brun059** [comment] 2017-07-02 20:59
thanks for looking at it. Actually, SMB to the same server and files at the same time worked from the same device using other apps (FX file explorer), I assume the crash report is a leftover from an earlier crash of PhotoCloud (I'm ok with closing it though)
